[phases.setup]
nixPkgs = ["curl", "bash"]

[phases.build]
cmds = [
    "curl -fsSL https://deno.land/install.sh | bash -s v1.46.3",
    "~/.deno/bin/deno --version",
    "~/.deno/bin/deno cache src/routes/index.ts",
]

[start]
cmd = "~/.deno/bin/deno task start"
